# Generated by ts2python version 0.8.0 on 2025-08-08 21:59:50.122816
# compatibility level: Python 3.7 and above


from __future__ import annotations


import sys
from enum import Enum, IntEnum

from typing import Union, Optional, Any, Generic, TypeVar, Callable, List, \
    Iterable, Iterator, Tuple, Dict, Awaitable


try:
    from ts2python.typeddict_shim import TypedDict, GenericTypedDict, NotRequired, Literal, \
        ReadOnly, TypeAlias
    # Override typing.TypedDict for Runtime-Validation
except ImportError:
    print("Module ts2python.typeddict_shim not found. Only coarse-grained "
          "runtime type-validation of TypedDicts possible")
    try:
        from typing import TypedDict, Literal
    except ImportError:
        try:
            from ts2python.typing_extensions import TypedDict, Literal
        except ImportError:
            print(f'Please install the "typing_extensions" module via the shell '
                  f'command "# pip install typing_extensions" before running '
                  f'{__file__} with Python-versions <= 3.8!')
    try:
        from typing_extensions import NotRequired, ReadOnly, TypeAlias
    except ImportError:
        NotRequired = Optional
        ReadOnly = Union
        TypeAlias = Any
    GenericMeta = type
    class _GenericTypedDictMeta(GenericMeta):
        def __new__(cls, name, bases, ns, total=True):
            return type.__new__(_GenericTypedDictMeta, name, (dict,), ns)
        __call__ = dict
    GenericTypedDict = _GenericTypedDictMeta('TypedDict', (dict,), {})
    GenericTypedDict.__module__ = __name__


source_hash__ = "a5b117b44c7a4603542b28361db02bee"


##### BEGIN OF ts2python generated code


# Defines an integer number in the range of -2^31 to 2^31 - 1.


##### END OF ts2python generated code
