name = "ts2python"
__title__ = "ts2python"
__description__ = "Transpiler for Typescript-interfaces to Python TypedDicts"
__url__ = 'https://github.com/jecki/ts2python'
__uri__ = __url__
__author__ = "Eckhart Arnold"
__email__ = "eckhart.arnold@posteo.de"
__license__ = "http://www.apache.org/licenses/LICENSE-2.0"
__copyright__ = "Copyright (c) 2021 Eckhart Arnold"
