
[config]
ts2python.RenderAnonymous          = "local"
ts2python.UsePostponedEvaluation   = True
ts2python.UseTypeUnion             = True
ts2python.UseExplicitTypeAlias     = True
ts2python.UseTypeParameters        = False
ts2python.UseLiteralType           = True
ts2python.UseVariadicGenerics      = True
ts2python.UseNotRequired           = True
ts2python.AllowReadOnly            = True
ts2python.AssumeDeferredEvaluation = False
ts2python.KeepComments    = True

[match:declarations_block]
M1: """{
        users: User;
        media: Media;
        pages: Page;
        tools: Tool;
        resources: Resource;
        tags: Tag;
        'payload-kv': PayloadKv;
        'payload-locked-documents': PayloadLockedDocument;
        'payload-preferences': PayloadPreference;
        'payload-migrations': PayloadMigration;
      }"""
;
;[match:document]
;M1: """export interface Config {
;      auth: {
;        users: UserAuthOperations;
;      };
;      blocks: {};
;      collections: {
;        users: User;
;        media: Media;
;        pages: Page;
;        tools: Tool;
;        resources: Resource;
;        tags: Tag;
;        'payload-kv': PayloadKv;
;        'payload-locked-documents': PayloadLockedDocument;
;        'payload-preferences': PayloadPreference;
;        'payload-migrations': PayloadMigration;
;      };
;      collectionsJoins: {};
;      collectionsSelect: {
;        users: UsersSelect<false> | UsersSelect<true>;
;        media: MediaSelect<false> | MediaSelect<true>;
;        pages: PagesSelect<false> | PagesSelect<true>;
;        tools: ToolsSelect<false> | ToolsSelect<true>;
;        resources: ResourcesSelect<false> | ResourcesSelect<true>;
;        tags: TagsSelect<false> | TagsSelect<true>;
;        'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
;        'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
;        'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
;        'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
;      };
;      db: {
;        defaultIDType: string;
;      };
;      fallbackLocale: null;
;      globals: {
;        settings: Setting;
;        footer: Footer;
;      };
;      globalsSelect: {
;        settings: SettingsSelect<false> | SettingsSelect<true>;
;        footer: FooterSelect<false> | FooterSelect<true>;
;      };
;      locale: null;
;      widgets: {
;        collections: CollectionsWidget;
;      };
;      user: User;
;      jobs: {
;        tasks: unknown;
;        workflows: unknown;
;      };
;    }"""